### ISSUE TITLE
Visualize hierarchy of our keywords + rollback function to remove branches

### ISSUE THREAD

**Issue by chaoran-chen** [icebreaker-science/network#2]
By joining our keywords with Wikidata (see for example https://www.wikidata.org/wiki/Q862228), we have already obtained some information about the class hierarchy of the entities. Especially, we have used the Wikidata properties _instance of_ and _subclass of_.

Let's now visualize the hierarchy as a tree!

**Comment by vordemann** [comment]
The following todos are added to this issue:

- [ ] Add functionality that makes the visualized hierarchy searchable and editable. This is important so that one can identify good categories and remove useless subbranches. How to implement this is up to the developer. A comprehensive csv export/import is also okay.
- [ ] Rollback function that updates database with changes made in the hierarchy.
